#NumPy is a Python library.NumPy is used for working with arrays.NumPy is short for "Numerical Python".

In [1]:
import numpy as np

In [3]:
#Creating an array with .array()
grid = np.array([1,2,3,4,5])
print(grid)
print(type(grid))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#using tuple to create a Numpy array
grid1 = np.array((12,34,5,6,78,8,0))
print(grid1)

[12 34  5  6 78  8  0]


Dimesion in arrays -- A dimension in arrays is one level of array depth (nested arrays).

In [6]:
#1. 0-D Arrays
odarray = np.array(43)
print(odarray)

43


In [7]:
#2. 1-D Arrays
onedarray = np.array([1,2,3,4,5,7])
print(onedarray)

[1 2 3 4 5 7]


In [8]:
#3. 2-D Arrays -- These are often used to represent matrix or 2nd order tensors.
twodarrays = np.array([[1,2,3],[4,5,6]])
print(twodarrays)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3-D Arrays -- These are often used to represent a 3rd order tensor.
threedarrays = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(threedarrays)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
#Check Number of Dimensions? --ndim :attribute that returns an integer that tells us how many dimensions the array have.
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [11]:
#Higher Dimensional Arrays -- define using the ndim arguement
arr = np.array([13,34,5,6,6,7],ndmin=5)
print(arr)

[[[[[13 34  5  6  6  7]]]]]


NumPy Array Indexing

In [14]:
#index the first and second item in the array
arr= np.array([1,2,3,4])
print(arr[0])

print(arr[1])

#Add the 3rd and 4th elements in array
print(arr[2]+ arr[3])

1
2
7


In [18]:
#Accessing dimesional arrays
#2-D arrays -- element on first row second column
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0,1])
print('3rd element on 2nd row: ', arr[1,2])

#Access the element on the 2nd row, 5th column:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on second row: ', arr[1,4])

2nd element on 1st row:  2
3rd element on 2nd row:  8
5th element on second row:  10


In [23]:
#3-D arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)

#Access the third element of the second array of the first array:
print(arr[0,1,2])
#Access 9
print(arr[1,0,2])

#Access 11
print(arr[1,1,1])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
9
11


In [24]:
#Negative Indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10
