#NumPy is a Python library.NumPy is used for working with arrays.NumPy is short for "Numerical Python".

In [1]:
import numpy as np

In [3]:
#Creating an array with .array()
grid = np.array([1,2,3,4,5])
print(grid)
print(type(grid))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#using tuple to create a Numpy array
grid1 = np.array((12,34,5,6,78,8,0))
print(grid1)

[12 34  5  6 78  8  0]


Dimesion in arrays -- A dimension in arrays is one level of array depth (nested arrays).

In [6]:
#1. 0-D Arrays
odarray = np.array(43)
print(odarray)

43


In [7]:
#2. 1-D Arrays
onedarray = np.array([1,2,3,4,5,7])
print(onedarray)

[1 2 3 4 5 7]


In [8]:
#3. 2-D Arrays -- These are often used to represent matrix or 2nd order tensors.
twodarrays = np.array([[1,2,3],[4,5,6]])
print(twodarrays)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3-D Arrays -- These are often used to represent a 3rd order tensor.
threedarrays = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(threedarrays)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
#Check Number of Dimensions? --ndim :attribute that returns an integer that tells us how many dimensions the array have.
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [11]:
#Higher Dimensional Arrays -- define using the ndim arguement
arr = np.array([13,34,5,6,6,7],ndmin=5)
print(arr)

[[[[[13 34  5  6  6  7]]]]]


NumPy Array Indexing

In [14]:
#index the first and second item in the array
arr= np.array([1,2,3,4])
print(arr[0])

print(arr[1])

#Add the 3rd and 4th elements in array
print(arr[2]+ arr[3])

1
2
7


In [18]:
#Accessing dimesional arrays
#2-D arrays -- element on first row second column
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0,1])
print('3rd element on 2nd row: ', arr[1,2])

#Access the element on the 2nd row, 5th column:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on second row: ', arr[1,4])

2nd element on 1st row:  2
3rd element on 2nd row:  8
5th element on second row:  10


In [23]:
#3-D arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)

#Access the third element of the second array of the first array:
print(arr[0,1,2])
#Access 9
print(arr[1,0,2])

#Access 11
print(arr[1,1,1])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
9
11


In [24]:
#Negative Indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


**NumPy Array Slicing -- Slicing in python means taking elements from one given index to another given index.**

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [25]:
# The result includes the start index, but excludes the end index.
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [27]:
#Slice elements from index 4 to the end of the array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

#Slice elements from the beginning to index 4 (not included):
print(arr[:4])


[5 6 7]
[1 2 3 4]


In [29]:
#Steps in slicing --Use the step value to determine the step of the slicing:
#Return every other element from index 1 to index 5:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

print(arr[::2])

[2 4]
[1 3 5 7]


In [33]:
#Slicing 2-D Arrays
#select the second array(1) and then select the 2nd to third elements(1:4)
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

#select from both arrays(0:2(excluded)) and then select the third element
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])



[7 8 9]
[3 8]


**NumPy Data Types**

By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

**Below is a list of all data types in NumPy and the characters used to represent them.**

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [34]:
#checking the data type for arrays .dtype()
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)


<U6


In [35]:
#Creating Arrays With a Defined Data Type .example: np.array([],dtype='')
arr = np.array([1,23,4,5,6,7],dtype='S')
print(arr)
print(arr.dtype)


[b'1' b'23' b'4' b'5' b'6' b'7']
|S2


In [36]:
#Create an array with data type 4 bytes integer:
arr = np.array([1,2,3,4,4,5,6],dtype ='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 4 5 6]
int32


In [37]:
#Converting Data Type on Existing Arrays -- use the astype()
#Convert the float ot integers
arr = np.array([1.1,2.1,3.1,4.1])
newarr = arr.astype(int)
print(newarr)

[1 2 3 4]


**NumPy Array Copy vs View**
- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.


In [38]:
#copy -- Make a copy, change the original array, and display both arrays: The copy SHOULD NOT be affected by the changes made to the original array.
arr = np.array([1, 2, 3, 4, 5])
copyarray = arr.copy()
arr[0] = 42

print(arr)
print(copyarray)

[42  2  3  4  5]
[1 2 3 4 5]


In [39]:
#View -- Make a view, change the original array, and display both arrays:The view SHOULD be affected by the changes made to the original array.
arr = np.array([1, 2, 3, 4, 5])
viewarray = arr.view()
arr[0] = 42

print(arr)
print(viewarray)

#Make a view, change the view, and display both arrays:



[42  2  3  4  5]
[42  2  3  4  5]


NumPy Array Shape --NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.


In [40]:
#Array shape .shape()
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [42]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [43]:
#Reshaping arrays -- By reshaping we can add or remove dimensions or change number of elements in each dimension.
#convert 1-D array to 2-D array with 4,3 matrix
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarray = arr.reshape(4,3)
print(newarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [44]:
#Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarray1 = arr.reshape(2,3,2)
print(newarray1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [46]:
#Unknown Dimension -- Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
unkowndim = arr.reshape(2,2,-1)
print(unkowndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
#Flattening the arrays---Flattening array means converting a multidimensional array into a 1D array. use the .reshape(-1)
arr = np.array([[1, 2, 3], [4, 5, 6]])
onedimarray = arr.reshape(-1)
print(onedimarray)

[1 2 3 4 5 6]


NumPy Array Iterating -- Iterating means going through elements one by one.

In [49]:
#iterate through a 1-D array
arr = np.array([1,2,3])
for a in arr:
    print(a)

1
2
3


In [50]:
#Iterating 2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
for a in arr:
    print(a)

[1 2 3]
[4 5 6]


In [51]:
#To return the actual values, the scalars, we have to iterate the arrays in each dimension.
arr = np.array([[1, 2, 3], [4, 5, 6]])
for a in arr:
    for x in a:
        print(x)


1
2
3
4
5
6


In [53]:
#Iterating 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for a in arr:
    print(a)

#To return the actual values, the scalars, we have to iterate the arrays in each dimension.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for a in arr:
    for x in a:
        for y in x:
            print(y)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


In [54]:
#Iterating Arrays Using nditer() -- suitable for looping higher
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for a in np.nditer(arr):
    print(a)

1
2
3
4
5
6
7
8


In [56]:
#Iterating Array With Different Data Types
#Iterate through the array as a string:
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)


b'1'
b'2'
b'3'


In [57]:
#Enumerated Iteration Using ndenumerate() -- Enumeration means mentioning sequence number of somethings one by one.
#1-D array
arr = np.array([1, 2, 3])
for idx , x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [58]:
#2-D arrays
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx , x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


NumPy Joining Array  concatenate(),np.stack(),np.hstack(),np.vstack(),dstack()-- Joining means putting contents of two or more arrays in a single array.

In [61]:
#concatenate() - 1-D array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [63]:
#2-D array
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [64]:
#Joining Arrays Using Stack Functions -- np.stack()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [65]:
#Stacking Along Rows -- np.hstack()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [66]:
#Stacking Along Columns --np.vstack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]
