In [2]:
import numpy as np

Arrays VS lists

In [4]:
#Arrays vs List
#list
List = [1,2,24,5,5]
print(List)
#Arra
Array = np.array([1,2,24,5,5])
print(Array)

[1, 2, 24, 5, 5]
[ 1  2 24  5  5]


In [6]:
#looping list
for l in List:
    print(l)


1
2
24
5
5


In [7]:
#looping Array
for a in Array:
    print(a)

1
2
24
5
5


In [10]:
#Append list
List.append(8)
print(List)

[1, 2, 24, 5, 5, 8, 8, 8]


In [11]:
#Add 3 to each element in list
L2 =[]
for l in List:
    L2.append(l+3)

In [12]:
L2

[4, 5, 27, 8, 8, 11, 11, 11]

In [13]:
L2

[4, 5, 27, 8, 8, 11, 11, 11]

In [15]:
#multiply thru the list by 2
L2 =[]
for l in List:
    L2.append(l**2)
L2

[1, 4, 576, 25, 25, 64, 64, 64]

In [17]:
#multiply thru Arrays
Array**2

array([  1,   4, 576,  25,  25])

The Dot Product

In [18]:
a = np.array([1,2])
b = np.array([3,4])


In [19]:
#using zip()
dot = 0
for e, f in zip(a,b):
    dot += e*f
dot

11

In [20]:
#using for
dot = 0
for i in range(len(a)):
    dot +=a[i] * b[i]
dot

11

In [21]:
#sum
np.sum(a*b)

11

In [22]:
np.dot(a,b)

11

In [24]:
sqrtproduct = np.sqrt(sum(a*b))
sqrtproduct

3.3166247903554

Speedtest -- python list vs Arrays ; Arrays are faster to run and compute

Matrices

In [25]:
#Lists
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [33]:
L[0]
L[0][1]
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [28]:
#Array
A =np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [30]:
#select 2
A[0,1]
#Select everything in row
A[:,0]

array([1, 3])

In [32]:
#Transpose
A.T
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [35]:
#Inverse using linear algebra .np.linalg.inv()
np.linalg.inv(A)

#Determinant --np.linalg.det()
np.linalg.det(A)


-2.0000000000000004

In [36]:
#inverse -- np.linalg.inv()
np.linalg.inv(A).dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [37]:
#Eigen values and vectors --np.linalg.eig()
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

Solving linear algebra

In [39]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])

np.linalg.solve(A,b)

array([1500.,  700.])

Generating Data -- Random

In [40]:
import random

In [41]:
np.random.random((2,3))

array([[0.32402019, 0.92733154, 0.22071972],
       [0.74894644, 0.66449462, 0.42740474]])

In [44]:
R=np.random.rand(1000)
np.mean(R)
np.var(R)

0.083950828945687